apiVersion: v1
kind: Service
metadata:
  name: content-engine
spec:
  selector:
    app: web
    
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP 
      port: 80
      targetPort: 8080